import { Fate } from "./types";

export const fates = [
  {
    name: "飞艇英雄",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["赛琳", "阿尔比", "克莉丝汀"],
  },
  {
    name: "德雷克天空盗贼团",
    type: "攻击",
    incresePerLevel: 2.5,
    heros: ["赛琳", "德雷克", "达娜"],
  },
  {
    name: "摩尔帝国骑士团",
    type: "生命",
    incresePerLevel: 3,
    heros: ["格罗丽亚", "杰克", "克莉丝汀"],
  },
  {
    name: "守护泰莎的盾牌",
    type: "防御",
    incresePerLevel: 1,
    heros: ["艾莉诺", "奥蕾利亚"],
  },
  {
    name: "燃烧的血液",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["纳林", "维克", "劳伦特"],
  },
  {
    name: "今世之约",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["苏沃", "雪儿"],
  },
  {
    name: "亡者代言人",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["威尔伯", "戴登"],
  },
  {
    name: "伊甸园之东",
    type: "攻击",
    incresePerLevel: 0.8,
    heros: ["西尔维亚", "尤依"],
  },
  {
    name: "先贤的风采",
    type: "攻击",
    incresePerLevel: 1.3,
    heros: ["善花", "巴欧"],
  },
  {
    name: "森林的主人们",
    type: "生命",
    incresePerLevel: 1.5,
    heros: ["芙萝拉", "碧翠丝", "班杰明"],
  },
  {
    name: "太阳的后代",
    type: "生命",
    incresePerLevel: 2.5,
    heros: ["拉希德", "萨曼达", "拉姆塞斯"],
  },
  {
    name: "帅气的男子",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["克努特", "德雷克", "伊戈尔", "路德威"],
  },
  {
    name: "松松软软",
    type: "穿透",
    incresePerLevel: 0.9,
    heros: ["PQ", "贝尔纳多", "虎狼"],
  },
  {
    name: "超级明星",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["法比安", "米兰达", "安娜"],
  },
  {
    name: "兽人的日常",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["露露", "笑笑", "彩肖尔"],
  },
  {
    name: "花之精灵",
    type: "防御",
    incresePerLevel: 2,
    heros: ["樱花", "紫丁香", "百合", "西亚信"],
  },
  {
    name: "深邃的海底~",
    type: "穿透",
    incresePerLevel: 1.75,
    heros: ["艾莉娅", "阿勒格罗", "柯妮", "马塞洛"],
  },
  {
    name: "符文争夺战",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["米莉", "洁斯", "阿卡妮", "阿圭尔"],
  },
  {
    name: "雾林守护者",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["比比", "水星", "猎奥坎", "米克"],
  },
  {
    name: "冰冷的心脏",
    type: "生命",
    incresePerLevel: 1.2,
    heros: ["巴赫一号", "巴赫二号", "巴赫三号", "巴赫四号"],
  },
  {
    name: "水之韵律",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["彩肖尔", "艾莉娅", "洁斯"],
  },
  {
    name: "清风之律",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["笑笑", "柯妮", "阿圭尔"],
  },
  {
    name: "大地之盟",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["伊森", "米莉", "科拉汉得"],
  },
  {
    name: "火之燎原",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["阿勒格罗", "阿卡妮", "克特"],
  },
  {
    name: "水之领域",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["香草", "猎犬", "苏菲"],
  },
  {
    name: "枪手之魂",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["达娜", "梅", "卡罗"],
  },
  {
    name: "拳拳到肉",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["贝尔纳多", "波浪", "虎狼"],
  },
  {
    name: "安全守护",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["杰克", "西尔维亚", "莫心"],
  },
  {
    name: "风之速度",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["芙萝拉", "碧翠丝", "尤依"],
  },
  {
    name: "大地之姿",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["璐儿", "拉姆塞斯", "班杰明"],
  },
  {
    name: "魔法相遇",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["PQ", "默鲁", "莫里斯"],
  },
  {
    name: "喜气洋洋",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["吕布", "貂蝉"],
  },
  {
    name: "新年快乐",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["吕布", "貂蝉", "黎露"],
  },
  {
    name: "风之轻语",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["面珑", "雷克斯", "薇笑"],
  },
  {
    name: "炽热之绊",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["玫瑰琳", "泡泡糖", "亨利"],
  },
  {
    name: "以盾为进",
    type: "生命",
    incresePerLevel: 3,
    heros: ["艾莉诺", "赛琳", "杰克"],
  },
  {
    name: "春暖花开",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["格罗丽亚", "马塞洛", "百合"],
  },
  {
    name: "疯狂进行曲",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["西亚信", "猎犬", "法蒂玛"],
  },
  {
    name: "圣贤的风采",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["巴欧", "善花", "樱花"],
  },
  {
    name: "花香四溢",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["紫丁香", "璐儿", "百合"],
  },
  {
    name: "太阳的后裔",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["拉希德", "阿尔比", "维克"],
  },
  {
    name: "金牌守卫",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["艾莉诺", "奥蕾利亚", "杰克"],
  },
  {
    name: "唯快不破",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["彩肖尔", "柯妮", "拉希德", "格罗丽亚"],
  },
  {
    name: "水域羁绊",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["墨熙", "让路易", "纳姆维尔"],
  },
  {
    name: "魔灵降世",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["炎之盾", "水门狱"],
  },
  {
    name: "大地之魂",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["芬舍尔", "卡雅", "尖牙"],
  },
  {
    name: "攻守易型",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["尖牙", "奥蕾利亚", "卡雅"],
  },
  {
    name: "大爱吴疆",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["大乔", "孙策"],
  },
  {
    name: "电灯泡",
    type: "攻击",
    incresePerLevel: 3,
    heros: ["大乔", "孙策", "霜夜"],
  },
  {
    name: "三国无双",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["吕布", "貂蝉", "大乔", "孙策"],
  },
  {
    name: "灵珠转世",
    type: "攻击",
    incresePerLevel: 2,
    heros: ["土灵现", "风息幕"],
  },
  {
    name: "少年英雄，逆天改命！",
    type: "攻击",
    incresePerLevel: 4,
    heros: ["炎之盾", "水门狱", "土灵现", "风息幕"],
  },
] as const satisfies Fate[];

export const FATE_NAMES = fates.map((f) => f.name);
