import { AWAKENING_TYPES_DATA } from "./consts";
import { Hero } from "./types";

const heros = [
  {
    name: "莫心",
    initialRate: 1,
    initialData: {
      attack: 30,
    },
    element: "火",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "阿尔比",
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    element: "火",
    job: "坦克",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "玫瑰琳",
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    element: "火",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "纳林",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "扎克",
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    element: "火",
    job: "近战",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "维克",
    initialRate: 2,
    initialData: {
      attack: 60,
    },
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "露露",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "火",
    job: "近战",
    awakening: "穿透",
    discovery_all: "攻击",
  },
  {
    name: "巴赫一号",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "火",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "克特",
    initialRate: 3,
    initialData: {
      attack: 90,
    },
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "亨利",
    initialRate: 3,
    initialData: {
      attack: 100,
    },
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "炎之盾",
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    element: "火",
    job: "近战",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "米兰达",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "火",
    job: "远程",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "梅",
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    element: "火",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "劳伦特",
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    element: "火",
    job: "远程",
    awakening: "穿透",
    discovery_all: "生命",
  },
  {
    name: "萨曼达",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "比比",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "阿卡妮",
    initialRate: 3,
    initialData: {
      attack: 75,
    },
    element: "火",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "法比安",
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    element: "火",
    job: "辅助",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "格罗丽亚",
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    element: "火",
    job: "辅助",
    awakening: "攻击速度",
    discovery_all: "防御",
  },
  {
    name: "樱花",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "火",
    job: "辅助",
    awakening: "暴击伤害",
    discovery_all: "防御",
  },
  {
    name: "阿勒格罗",
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    element: "火",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "防御",
  },
  {
    name: "泡泡糖",
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    element: "火",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "艾莉诺",
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    element: "水",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "贝尔纳多",
    initialRate: 2,
    initialData: {
      attack: 40,
    },
    element: "水",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "香草",
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    element: "水",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "苏沃",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "马塞洛",
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    element: "水",
    job: "近战",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "德雷克",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "水",
    job: "近战",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "伊戈尔",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "水星",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "巴赫二号",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "水",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "洁斯",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "水",
    job: "近战",
    awakening: "暴击抵抗率",
    discovery_all: "暴击率",
  },
  {
    name: "让路易",
    initialRate: 3,
    initialData: {
      attack: 140,
    },
    element: "水",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "攻击",
  },
  {
    name: "水门狱",
    initialRate: 3,
    initialData: {
      attack: 144,
    },
    element: "水",
    job: "近战",
    awakening: "防御",
    discovery_all: "穿透",
  },
  {
    name: "雪儿",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "水",
    job: "远程",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "波浪",
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    element: "水",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "达娜",
    initialRate: 2,
    initialData: {
      attack: 50,
    },
    element: "水",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "生命",
  },
  {
    name: "彩肖尔",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "水",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "生命",
  },
  {
    name: "墨熙",
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    element: "水",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "猎犬",
    initialRate: 3,
    initialData: {
      attack: 160,
    },
    element: "水",
    job: "远程",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "莫里斯",
    initialRate: 1,
    initialData: {
      attack: 25,
    },
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "法蒂玛",
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    element: "水",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "防御",
  },
  {
    name: "西亚信",
    initialRate: 3,
    initialData: {
      attack: 43,
    },
    element: "水",
    job: "辅助",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "艾莉娅",
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "纳姆维尔",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "水",
    job: "辅助",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "苏菲",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "杰克",
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "班杰明",
    initialRate: 2,
    initialData: {
      attack: 25,
    },
    element: "土",
    job: "坦克",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "芬舍尔",
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "科拉汉得",
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "克莉丝汀",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "土",
    job: "近战",
    awakening: "穿透",
    discovery_all: "攻击",
  },
  {
    name: "虎狼",
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "拉希德",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "土",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "猎奥坎",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "伊森",
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    element: "土",
    job: "近战",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "巴赫三号",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "土",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "米莉",
    initialRate: 3,
    initialData: {
      attack: 75,
    },
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "尖牙",
    initialRate: 3,
    initialData: {
      attack: 100,
    },
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "吕布",
    initialRate: 3,
    initialData: {
      attack: 145,
    },
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "貂蝉",
    initialRate: 3,
    initialData: {
      attack: 110,
    },
    element: "土",
    job: "近战",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "拉姆塞斯",
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    element: "土",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "穿透",
  },
  {
    name: "卡罗",
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    element: "土",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "生命",
  },
  {
    name: "威尔伯",
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    element: "土",
    job: "远程",
    awakening: "暴击率",
    discovery_all: "穿透",
  },
  {
    name: "戴登",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "土",
    job: "远程",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "卡雅",
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    element: "土",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "默鲁",
    initialRate: 2,
    initialData: {
      attack: 30,
    },
    element: "土",
    job: "辅助",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "安娜",
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    element: "土",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "防御",
  },
  {
    name: "百合",
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    element: "土",
    job: "辅助",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "璐儿",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "土",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "攻击",
  },
  {
    name: "黎露",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "土",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "土灵现",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "土",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "奥蕾利亚",
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "西尔维亚",
    initialRate: 2,
    initialData: {
      attack: 40,
    },
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "雷克斯",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "霜夜",
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    element: "风",
    job: "坦克",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "尤依",
    initialRate: 1,
    initialData: {
      attack: 60,
    },
    element: "风",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "巴欧",
    initialRate: 1,
    initialData: {
      attack: 55,
    },
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "克努特",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "路德威",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "巴赫四号",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "风",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "面珑",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "风",
    job: "近战",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "薇笑",
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    element: "风",
    job: "近战",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "孙策",
    initialRate: 3,
    initialData: {
      attack: 150,
    },
    element: "风",
    job: "近战",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "赛琳",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "风",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "芙萝拉",
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "PQ",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "风",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "紫丁香",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "风",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "米克",
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "柯妮",
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    element: "风",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "阿圭尔",
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    element: "风",
    job: "远程",
    awakening: "暴击率",
    discovery_all: "穿透",
  },
  {
    name: "风息幕",
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    element: "风",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "大乔",
    initialRate: 3,
    initialData: {
      attack: 200,
    },
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "碧翠丝",
    initialRate: 2,
    initialData: {
      attack: 35,
    },
    element: "风",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "善花",
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    element: "风",
    job: "辅助",
    awakening: "暴击伤害",
    discovery_all: "防御",
  },
  {
    name: "笑笑",
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    element: "风",
    job: "辅助",
    awakening: "生命",
    discovery_all: "攻击",
  },
] as const satisfies Hero[];

export const HERO_NAMES = heros.map((h) => h.name);

export function getAwakeningDisplayString(hero: Hero) {
  const increment = AWAKENING_TYPES_DATA[hero.awakening][hero.initialRate - 1];
  return `${hero.awakening}+${increment}${
    hero.awakening !== "攻击速度" ? "%" : ""
  }`;
}

export default heros;
