import { AWAKENING_TYPES_DATA } from "./consts";
import { Hero } from "./types";

const heros = [
  {
    name: "莫心",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 30,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "金属获得量", increment: 10 },
      { type: "生命", increment: 3 },
    ],
    element: "火",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "阿尔比",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "金属获得量", increment: 10 },
    ],
    element: "火",
    job: "坦克",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "玫瑰琳",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "纳林",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "扎克",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "维克",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "露露",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "火",
    job: "近战",
    awakening: "穿透",
    discovery_all: "攻击",
  },
  {
    name: "巴赫一号",
    alias: ["火迈巴赫"],
    initialRate: 1,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "火",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "克特",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 90,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "亨利",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 100,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "炎之盾",
    alias: ["火哪吒"],
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "生命", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "瓦尔基里",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 100,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "近战",
    awakening: "穿透",
    discovery_all: "暴击率",
  },
  {
    name: "米兰达",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "火",
    job: "远程",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "梅",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "火",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "劳伦特",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "远程",
    awakening: "穿透",
    discovery_all: "生命",
  },
  {
    name: "萨曼达",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "比比",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "阿卡妮",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 75,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "火",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "拉布琳",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "杜莎利斯",
    alias: ["美杜莎"],
    initialRate: 3,
    initialData: {
      attack: 300,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "火",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "法比安",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "攻击", increment: 5 },
      { type: "跳过关卡的概率", increment: 1 },
    ],
    element: "火",
    job: "辅助",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "格罗丽亚",
    alias: ["火旗"],
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "攻击", increment: 5 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "火",
    job: "辅助",
    awakening: "攻击速度",
    discovery_all: "防御",
  },
  {
    name: "樱花",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "火",
    job: "辅助",
    awakening: "暴击伤害",
    discovery_all: "防御",
  },
  {
    name: "阿勒格罗",
    alias: ["章鱼"],
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "火",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "防御",
  },
  {
    name: "泡泡糖",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "火",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "帕拉斯",
    alias: ["雅典娜"],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "火",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "艾莉诺",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "水",
    job: "坦克",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "贝尔纳多",
    alias: ["白熊"],
    initialRate: 2,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "香草",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "水",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "苏沃",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "马塞洛",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "攻击", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "德雷克",
    alias: ["海盗"],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "伊戈尔",
    alias: ["水斧"],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "水星",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "巴赫二号",
    alias: ["水迈巴赫"],
    initialRate: 1,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "水",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "洁斯",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "暴击抵抗率",
    discovery_all: "暴击率",
  },
  {
    name: "让路易",
    alias: ["路易"],
    initialRate: 3,
    initialData: {
      attack: 140,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "水",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "攻击",
  },
  {
    name: "水门狱",
    alias: ["水哪吒"],
    initialRate: 3,
    initialData: {
      attack: 144,
    },
    rateUpEffects: [
      { type: "防御", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "防御", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "防御", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "防御",
    discovery_all: "穿透",
  },
  {
    name: "耶梦加得",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 80,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "雪儿",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "水",
    job: "远程",
    awakening: "生命",
    discovery_all: "穿透",
  },
  {
    name: "波浪",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "水",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "达娜",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "水",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "生命",
  },
  {
    name: "彩肖尔",
    alias: ["白猫"],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "生命",
  },
  {
    name: "墨熙",
    alias: ["毛笔人"],
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "巴比尔",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "猎犬",
    alias: ["牢犬"],
    initialRate: 3,
    initialData: {
      attack: 160,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "水",
    job: "远程",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "泰西斯",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 80,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "水",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "莫里斯",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 25,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "魔力获得量", increment: 10 },
    ],
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "法蒂玛",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "攻击", increment: 5 },
      { type: "跳过关卡的概率", increment: 1 },
    ],
    element: "水",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "防御",
  },
  {
    name: "西亚信",
    alias: ["少爷"],
    initialRate: 3,
    initialData: {
      attack: 43,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "水",
    job: "辅助",
    awakening: "暴击率",
    discovery_all: "攻击",
  },
  {
    name: "艾莉娅",
    alias: ["人鱼"],
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "纳姆维尔",
    alias: ["新水辅"],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "暴击抵抗率", increment: 1 },
    ],
    element: "水",
    job: "辅助",
    awakening: "防御",
    discovery_all: "防御",
  },
  {
    name: "苏菲",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "穿透", increment: 3 },
      { type: "魔力获得量", increment: 10 },
    ],
    element: "水",
    job: "辅助",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "伊莉丝",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 80,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "水",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "杰克",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 20,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "金属获得量", increment: 10 },
    ],
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "班杰明",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 25,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "坦克",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "芬舍尔",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 30,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "科拉汉得",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "土",
    job: "坦克",
    awakening: "防御",
    discovery_all: "生命",
  },
  {
    name: "周瑜",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 110,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "坦克",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "克莉丝汀",
    alias: ["土剑"],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "土",
    job: "近战",
    awakening: "穿透",
    discovery_all: "攻击",
  },
  {
    name: "虎狼",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "拉希德",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "猎奥坎",
    alias: ["牢坎"],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "伊森",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "巴赫三号",
    alias: ["土迈巴赫"],
    initialRate: 1,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "土",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "米莉",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 75,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "金属获得量", increment: 10 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "玛莉",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "土",
    job: "近战",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "风铃草",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "尖牙",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 100,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "艾琳娜",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 110,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 3 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "吕布",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 145,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "貂蝉",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 110,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "近战",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "拉姆塞斯",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "土",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "穿透",
  },
  {
    name: "卡罗",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "土",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "生命",
  },
  {
    name: "威尔伯",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "土",
    job: "远程",
    awakening: "暴击率",
    discovery_all: "穿透",
  },
  {
    name: "戴登",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "土",
    job: "远程",
    awakening: "攻击",
    discovery_all: "穿透",
  },
  {
    name: "卡雅",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 120,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "土",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "黄晶",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "魔力获得量", increment: 10 },
    ],
    element: "土",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "暴击率",
  },
  {
    name: "默鲁",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 30,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "土",
    job: "辅助",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "安娜",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "攻击", increment: 5 },
      { type: "跳过关卡的概率", increment: 1 },
    ],
    element: "土",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "防御",
  },
  {
    name: "百合",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "辅助",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "璐儿",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "土",
    job: "辅助",
    awakening: "暴击抵抗率",
    discovery_all: "攻击",
  },
  {
    name: "黎露",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "土",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "土灵现",
    alias: ["土哪吒"],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "土",
    job: "辅助",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "小乔",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 145,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "土",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "奥蕾利亚",
    alias: ["风盾"],
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "防御",
  },
  {
    name: "西尔维亚",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "生命",
  },
  {
    name: "优森",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 50,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "坦克",
    awakening: "暴击伤害",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "雷克斯",
    alias: ["厨子"],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "风",
    job: "坦克",
    awakening: "生命",
    discovery_all: "暴击抵抗率",
  },
  {
    name: "霜夜",
    alias: ["东东"],
    initialRate: 3,
    initialData: {
      attack: 25,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "风",
    job: "坦克",
    awakening: "穿透",
    discovery_all: "防御",
  },
  {
    name: "尤依",
    alias: ["ue"],
    initialRate: 1,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "风",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "巴欧",
    alias: [],
    initialRate: 1,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "攻击", increment: 2 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
    ],
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "克努特",
    alias: ["风拳"],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "路德威",
    alias: ["风斧"],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "近战",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "巴赫四号",
    alias: ["风迈巴赫"],
    initialRate: 1,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "生命", increment: 2 },
      { type: "生命", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "风",
    job: "近战",
    awakening: "生命",
    discovery_all: "暴击率",
  },
  {
    name: "面珑",
    alias: ["面龙"],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "风",
    job: "近战",
    awakening: "防御",
    discovery_all: "攻击",
  },
  {
    name: "卡玛尔",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 150,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "近战",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "薇笑",
    alias: ["微笑"],
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "近战",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "孙策",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 150,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "近战",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "赛琳",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "暴击率", increment: 1 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "芙萝拉",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 55,
    },
    rateUpEffects: [
      { type: "攻击", increment: 3 },
      { type: "穿透", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "PQ",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "风",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "紫丁香",
    alias: ["香香"],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "穿透",
    discovery_all: "穿透",
  },
  {
    name: "米克",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 65,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "生命",
  },
  {
    name: "柯妮",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 60,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击速度", increment: 3 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "阿圭尔",
    alias: ["圭圭", "龟龟"],
    initialRate: 3,
    initialData: {
      attack: 70,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "暴击抵抗率", increment: 1 },
      { type: "魔石获得量", increment: 10 },
    ],
    element: "风",
    job: "远程",
    awakening: "暴击率",
    discovery_all: "穿透",
  },
  {
    name: "柳月",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 130,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "生命", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击速度",
    discovery_all: "穿透",
  },
  {
    name: "风息幕",
    alias: ["风哪吒"],
    initialRate: 3,
    initialData: {
      attack: 175,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "攻击", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "暴击伤害",
    discovery_all: "暴击率",
  },
  {
    name: "大乔",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 200,
    },
    rateUpEffects: [
      { type: "防御", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "防御", increment: 5 },
      { type: "穿透", increment: 5 },
      { type: "防御", increment: 5 },
    ],
    element: "风",
    job: "远程",
    awakening: "攻击",
    discovery_all: "暴击率",
  },
  {
    name: "碧翠丝",
    alias: [],
    initialRate: 2,
    initialData: {
      attack: 35,
    },
    rateUpEffects: [
      { type: "生命", increment: 3 },
      { type: "防御", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 3 },
      { type: "魔力获得量", increment: 10 },
    ],
    element: "风",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "攻击",
  },
  {
    name: "善花",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 35,
    },
    rateUpEffects: [
      { type: "生命", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "生命", increment: 5 },
      { type: "攻击", increment: 5 },
      { type: "跳过关卡的概率", increment: 1 },
    ],
    element: "风",
    job: "辅助",
    awakening: "暴击伤害",
    discovery_all: "防御",
  },
  {
    name: "笑笑",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "攻击", increment: 5 },
      { type: "防御", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "穿透", increment: 3 },
      { type: "攻击", increment: 5 },
    ],
    element: "风",
    job: "辅助",
    awakening: "生命",
    discovery_all: "攻击",
  },
  {
    name: "伊蕾莎",
    alias: [],
    initialRate: 3,
    initialData: {
      attack: 40,
    },
    rateUpEffects: [
      { type: "攻击", increment: 2 },
      { type: "生命", increment: 3 },
      { type: "生命", increment: 3 },
      { type: "攻击", increment: 5 },
      { type: "暴击伤害", increment: 5 },
    ],
    element: "风",
    job: "辅助",
    awakening: "攻击",
    discovery_all: "暴击抵抗率",
  },
] as const satisfies Hero[];

export const HERO_NAMES = heros.map((h) => h.name);

export function getAwakeningIncrement(hero: Hero) {
  return AWAKENING_TYPES_DATA[hero.awakening][hero.initialRate - 1];
}

export function getAwakeningDisplayString(hero: Hero) {
  const increment = getAwakeningIncrement(hero);
  return `${hero.awakening}+${increment}${
    hero.awakening !== "攻击速度" ? "%" : ""
  }`;
}

export default heros;
